apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f1dlgflcl-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:63d23788a2a66e7832f653a81849a7ae27b1716a@sha256:1b8c81d46fd7253f1d9b944908d70b0dcbb98590995dbcc1196d65ea327979b8
          name: container-image
